IMG_SIDE = 384
IMG_CHANNELS = 1
NUM_PATHOLOGY = 3
NUM_ORADS = 4
ORADS_VALUES = (2, 3, 4, 5)

CONTINUOUS_CLINICAL = (
    "age",
    "AFP",
    "CA125",
    "CA199",
    "CEA",
    "HE4",
    "maximum diameter(mm)",
)

BINARY_CLINICAL = (
    "Menopause",
    "Vaginalbleeding\n",
)

CLINICAL_FIELDS = CONTINUOUS_CLINICAL + BINARY_CLINICAL

PATHOLOGY_NAMES = ("benign", "malignant", "borderline")
PATHOLOGY_TO_IDX = {1: 0, 2: 1, 3: 2}

AUX_WEIGHT = 0.35
FOCAL_GAMMA = 2.0

EMBED_DIM = 512
CLIN_HIDDEN = 128
FUSION_DIM = 512
HEAD_DROPOUT = 0.25

SEED_A = 20240617
SEED_B = 524
SEED_C = 182

TRAIN_EPOCHS = 100
BATCH_SIZE = 16
LR = 1e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 4

INTERNAL_TOTAL = 524
EXTERNAL_TOTAL = 182
INTERNAL_TEST = 105
